# Deployment role for Symfony apps.
# Brought to you by Blacklight - http://www.blacklight.co.za/.
# Developer: Zander Janse van Rensburg <zjvren@geevcookie.com>
# License: MIT
#
# Handles the download of composer and the install command.
---
- name: Check if composer needs to be downloaded.
  stat: file={{ symfony_root_dir }}/composer.phar
  register: composer_file
  when: not symfony_composer_path

- name: Install composer
  get_url: url=https://getcomposer.org/composer.phar dest={{ symfony_root_dir }}/composer.phar mode=0755 validate_certs=no
  when: not symfony_composer_path and not composer_file.stat.exists

- name: Run composer install using downloaded version.
  shell: cd {{ symfony_root_dir }}/releases/{{ release_version.stdout }} && SYMFONY_ENV={{ symfony_env }} {{ symfony_php_path }} {{ symfony_root_dir }}/composer.phar install {{ symfony_composer_options }}
  when: not symfony_composer_path

- name: Run composer install using global version.
  shell: cd {{ symfony_root_dir }}/releases/{{ release_version.stdout }} && SYMFONY_ENV={{ symfony_env }} {{ symfony_composer_path }} install {{ symfony_composer_options }}
  when: symfony_composer_path != false
